### ISSUE TITLE
[Autumn] Dialog showing is not thread safe

### ISSUE THREAD

**Issue by XIII-th** [czyzby/gdx-lml#78] opened 2018-04-03 06:38 UTC
I found this issue when I implement asynchronous notifications. Crash happens when app is trying to show notification received in other thread and at the same time another notification is in preparing state (during of `AnnotatedViewDialogController.prepareDialogInstance()` operation).  
Method `prepareDialogInstance()` modify parser context adding _action container_:  
```java
public void prepareDialogInstance() {
    final LmlParser parser = interfaceService.getParser();
    if (actionContainer != null) {
        parser.getData().addActionContainer(getId(), actionContainer);
    }
    dialog = (Window) parser.createView(wrappedObject, Gdx.files.internal(dialogData.value())).first();
    if (actionContainer != null) {
        parser.getData().removeActionContainer(getId());
    }
}
```
My notification showing method also modify parser context adding _argument_:
```java
public void showNotification(Class<?> cls, String id) {
    LmlData lmlData = _interfaceService.getParser().getData();
    lmlData.addArgument(NOTIFICATION_ID, id);
    _interfaceService.showDialog(cls);
    lmlData.removeArgument(NOTIFICATION_ID);
}
```
In result I have error trace like this:
```java
com.github.czyzby.lml.util.LmlParsingException: Error occurred during parsing near line 5 of the original file: "friend_game_invite.lml" during parsing template part: "notification.lml" on line: 5 of its content. Template part is most likely an evaluated macro or argument result, extracted from the original template.
REASON: Unable to parse passed template due to an unexpected exception.
	Due implementation of the parser, the real problematic line might SLIGHTLY vary from the given line number(s), but exception message should be clear enough to find the actual error.
	Currently parsed template part:
2 |VALID| <!DOCTYPE dialog SYSTEM "../../dtd/lml1_8-min.dtd">
3 |VALID| <dialog style="dialog" onecolumn="true" pad="10">
4 |VALID|     <label id="message" multiline="true"/>
5 |ERROR|     <textbutton id="closeButton" onresult="close" tobuttontable="true">@OK</textbutton>
6 |     |     <textbutton id="retryButton" onresult="retry" tobuttontable="true">@TRY_AGAIN</textbutton>
7 |     | </dialog>

This template part was most likely evaluated during parsing this original template part (if a macro or an argument ends on this line, its content most likely causes the error): 
2 |VALID| <!DOCTYPE pushDialog SYSTEM "../../dtd/lml1_8-min.dtd">
3 |VALID| <pushDialog style="dialog" id="dialog" onecolumn="true" pad="10" pushId="{pushId}">
4 |VALID|     <label id="message" multiline="true"/>
5 |ERROR|     <textbutton onresult="accept">@ACCEPT</textbutton>
6 |     |     <textbutton onresult="reject">@REJECT</textbutton>
7 |     | </pushDialog>

If this is not enough to determine the error, call AbstractLmlParser#setLinesAmountPrintedOnException(int) with a suitable number. If you keep a lot of nested macros and want to see the whole invocation tree, try debugging through parsing and use getTemplateReader().toString() before exception occurs to check all current parsed template layers.
  at com.github.czyzby.lml.parser.impl.AbstractLmlParser.throwError (AbstractLmlParser.java:875)
  at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parseTemplate (DefaultLmlParser.java:106)
  at com.github.czyzby.lml.parser.impl.AbstractLmlParser.parseTemplate (AbstractLmlParser.java:197)
  at com.github.czyzby.lml.parser.impl.AbstractLmlParser.createView (AbstractLmlParser.java:232)
  at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewDialogController.prepareDialogInstance (AnnotatedViewDialogController.java:89)
  or                     .show (AnnotatedViewDialogController.java:89)
  at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.showDialog (InterfaceService.java:316)
<my code>
  at android.support.v4.content.LocalBroadcastManager.access$000 (LocalBroadcastManager.java:297)
  or                     .executePendingBroadcasts (LocalBroadcastManager.java:297)
  at android.support.v4.content.LocalBroadcastManager$1.handleMessage (LocalBroadcastManager.java:116)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5470)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: 
  at com.badlogic.gdx.utils.ObjectMap$Values.hasNext (ObjectMap.java:743)
  at com.github.czyzby.lml.parser.impl.AbstractLmlParser.parseAction (AbstractLmlParser.java:655)
  at com.github.czyzby.lml.parser.impl.attribute.table.dialog.OnResultLmlAttribute.process (OnResultLmlAttribute.java:33)
  at com.github.czyzby.lml.util.LmlUtilities.processAttributes (LmlUtilities.java:450)
  at com.github.czyzby.lml.parser.impl.tag.AbstractActorLmlTag.prepareActor (AbstractActorLmlTag.java:95)
  or                     .processTagAttributes (AbstractActorLmlTag.java:95)
  at com.github.czyzby.lml.parser.impl.tag.AbstractActorLmlTag.<init> (AbstractActorLmlTag.java:30)
  at com.github.czyzby.lml.parser.impl.tag.actor.TableLmlTag.<init> (TableLmlTag.java:17)
  at com.github.czyzby.lml.parser.impl.tag.actor.ButtonLmlTag.<init> (ButtonLmlTag.java:14)
  at com.github.czyzby.lml.parser.impl.tag.actor.TextButtonLmlTag.<init> (TextButtonLmlTag.java:18)
  at com.github.czyzby.lml.parser.impl.tag.actor.provider.TextButtonLmlTagProvider.create (TextButtonLmlTagProvider.java:14)
  at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processRegularTag (DefaultLmlParser.java:525)
  or                     .processTag (DefaultLmlParser.java:525)
  or                     .processTagEntity (DefaultLmlParser.java:525)
  at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parse (DefaultLmlParser.java:139)
  or                     .parseTemplate (DefaultLmlParser.java:139)
  at com.github.czyzby.lml.parser.impl.AbstractLmlParser.parseTemplate (AbstractLmlParser.java:197)
  at com.github.czyzby.lml.parser.impl.AbstractLmlParser.createView (AbstractLmlParser.java:232)
  at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewDialogController.prepareDialogInstance (AnnotatedViewDialogController.java:89)
  or                     .show (AnnotatedViewDialogController.java:89)
  at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.showDialog (InterfaceService.java:316)
<my code>
  at android.support.v4.content.LocalBroadcastManager.access$000 (LocalBroadcastManager.java:297)
  or                     .executePendingBroadcasts (LocalBroadcastManager.java:297)
  at android.support.v4.content.LocalBroadcastManager$1.handleMessage (LocalBroadcastManager.java:116)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5470)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
```

I have tried to fix it using `synchronized` block like this:  
```java
synchronized(_interfaceService) {
    //...
    _interfaceService.showDialog(cls);
    //...
}
```
and it works fine. But I guess same issue can happen during screen transition time while another thread is trying to show notification. 

I suppose, autumn framework should be responsible for asynchronous notification showing and screen transition.   
@czyzby I could try to solve this issue. What is your suggestion for implementing asynchronous notification support in autumn?

**Comment by czyzby** [comment] 2018-04-03 08:19
You should keep all UI-related code in the LibGDX application thread. Use LibGDX `postRunnable` or `OnEvent.forceMainThread` if you use Autumn event-related annotations.

**Comment by XIII-th** [comment] 2018-04-03 08:45
@czyzby if I understand you right, suggestion is 
```java
Gdx.app.postRunnable(() -> {
    LmlData lmlData = _interfaceService.getParser().getData();
    lmlData.addArgument(NOTIFICATION_ID, id);
    _interfaceService.showDialog(cls);
    lmlData.removeArgument(NOTIFICATION_ID);
});
```
This solution also can't solve issue because `DialogShowingAction` show dialog without wrapping `interfaceService.showDialog(viewDialogControllerClass)` into `Gdx.app.postRunnable()`.

**Comment by czyzby** [comment] 2018-04-03 09:54
It might make sense to modify `DialogShowingAction` then, but I'd have to look into its current usages. Seems like the actions should be executed on the main rendering thread already.

**Comment by XIII-th** [comment] 2018-04-03 10:05
@czyzby no. At least _onClick_ and _onChange_ (most frequently used) is not wrapped in `Gdx.app.postRunnable()`.

**Comment by czyzby** [comment] 2018-04-03 13:10
I think both `onClick` and `onChange` are both invoked on the main application thread, since events are handled on the main loop after each render (at least on [desktop](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplication.java#L217) not sure about the Android lifecycle). Can the error be reproduced both on the Android and desktop version? Maybe this is a LibGDX lifecycle error.

**Comment by XIII-th** [comment] 2018-04-04 18:56
I have checked it. It's true all input events is handling in main thread after runnable's queue.  In android implementation of LibGDX trace [from main thread](https://github.com/libgdx/libgdx/blob/e2fc555805d0c0d24c0534bdbd47c9383cd65930/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java#L493) to `DialogShowingAction` looks like:  
![image](https://user-images.githubusercontent.com/6898238/38327833-b42b1d6a-3862-11e8-8c3b-f886a9faedcc.png)

This mean we can safe show dialog from background thread  using `Gdx.app.postRunnable()` ([like here](https://github.com/czyzby/gdx-lml/issues/78#issuecomment-378175350)).

Thanks for help @czyzby. I think, we can close this issue

**Comment by czyzby** [comment] 2018-04-04 19:04
Well, runnables are also executed on the main loop by the same thread [on desktop](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplication.java#L210). If `postRunnable` does not work, you might be using LML parser concurrently somewhere else. Feel free to close this issue once you figure it out.

**Closed** 2018-04-05 03:11 UTC
Labels: autumn
