### ISSUE TITLE
pls help me  the gwt websoket Thread is not supported

### ISSUE THREAD

**Issue by chongbo2013** [czyzby/gdx-lml#84] opened 2018-07-30 10:12 UTC
pls help me  the gwt websoket Thread is not supported.
If I deal with the gdx drawing thread, it will cause blocking the drawing thread problem.

**Comment by chongbo2013** [comment] 2018-07-30 10:15
If I am in the gdx drawing thread, to process the data of the websocket, it will cause blocking.

**Comment by chongbo2013** [comment] 2018-08-02 01:58
yes. thank u very much.   can i add u  facebook

**Comment by czyzby** [comment] 2018-08-02 05:57
I don't use Facebook, but I usually respond to new GitHub issues pretty quickly. ;) Feel free to close this one if the problem is resolved.

**Comment by chongbo2013** [comment] 2018-08-03 03:05
thank u

**Closed** 2018-08-03 03:05 UTC
Labels: websocket
